- hosts: minhavm
  become: true
  gather_facts: true

  tasks:
    - name: Instalar o Docker e o Docker Compose
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Adicionar o diretório do Docker Compose ao PATH
      lineinfile:
        dest: "~/.bashrc"
        line: 'export PATH=$PATH:/usr/local/bin/docker-compose'
      become: yes

    - name: Ligar o Docker
      systemd:
        name: docker
        state: started
      become: yes

    - name: Adicionar usuário ao grupo docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Clonar o projeto Voting APP
      git:
        repo: https://github.com/Azure-Samples/azure-voting-app-redis.git
        dest: /home/vinimiquelin/azure-voting-app-redis

    - name: Acessar o diretório azure-voting-app-redis
      become_user: vinimiquelin
      shell: cd /home/vinimiquelin/azure-voting-app-redis

    - name: Executar o comando docker-compose up -d
      become_user: vinimiquelin
      shell: docker-compose up -d
      args:
        chdir: /home/vinimiquelin/azure-voting-app-redis